language: node_js
node_js:
  - "9"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: required

services:
  - docker

install:
  - npm install

script:
  - npm run build

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t zych1751/react-test .
  - docker push zych1751/react-test

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle  '

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: chaesongbucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: l10032503/chaesong
      branch: master